-- KulaAI Vision Field Accuracy & Animal Identity Validation Database Migration

CREATE TABLE IF NOT EXISTS `ai_vision_validation_sessions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` INT(11) NOT NULL,
  `session_code` VARCHAR(50) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `shed_id` INT(11) NOT NULL,
  `batch_id` INT(11) DEFAULT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME DEFAULT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'in_progress',
  `total_tested` INT(11) NOT NULL DEFAULT 0,
  `correct_count` INT(11) NOT NULL DEFAULT 0,
  `incorrect_count` INT(11) NOT NULL DEFAULT 0,
  `unknown_count` INT(11) NOT NULL DEFAULT 0,
  `needs_review_count` INT(11) NOT NULL DEFAULT 0,
  `accuracy_pct` DECIMAL(5,2) DEFAULT 0.00,
  `false_match_pct` DECIMAL(5,2) DEFAULT 0.00,
  `unknown_pct` DECIMAL(5,2) DEFAULT 0.00,
  `sample_status` VARCHAR(30) DEFAULT 'INSUFFICIENT DATA',
  `notes` TEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `shed_id` (`shed_id`),
  KEY `status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_vision_validation_records` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tenant_id` INT(11) NOT NULL,
  `validation_session_id` INT(11) NOT NULL,
  `actual_livestock_id` INT(11) DEFAULT NULL,
  `actual_tag_number` VARCHAR(100) DEFAULT NULL,
  `ai_livestock_id` INT(11) DEFAULT NULL,
  `ai_tag_number` VARCHAR(100) DEFAULT NULL,
  `identification_method` VARCHAR(50) DEFAULT 'ear_tag',
  `camera_angle` VARCHAR(30) DEFAULT 'FRONT',
  `lighting` VARCHAR(30) DEFAULT 'NORMAL_DAYLIGHT',
  `occlusion` VARCHAR(30) DEFAULT 'NONE',
  `tag_visibility` VARCHAR(30) DEFAULT 'VISIBLE',
  `ai_confidence` DECIMAL(5,2) DEFAULT 0.00,
  `is_repeat_test` TINYINT(1) DEFAULT 0,
  `verification_result` VARCHAR(30) NOT NULL DEFAULT 'CORRECT',
  `is_demo_data` TINYINT(1) DEFAULT 0,
  `raw_ai_response_json` LONGTEXT DEFAULT NULL,
  `visual_features_json` LONGTEXT DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `tenant_id` (`tenant_id`),
  KEY `validation_session_id` (`validation_session_id`),
  KEY `actual_livestock_id` (`actual_livestock_id`),
  KEY `verification_result` (`verification_result`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
